### ISSUE TITLE
In SRP Auth is it best practice to generate my own AuthenticationHelper.HEX_N?

### ISSUE THREAD

**Issue by jppdpf** [aws-samples/aws-cognito-java-desktop-app#13]
Hi,

I have a noob question, so in AuthenticationHelper class there's a variable HEX_N.

Is it best practice to generate my own large number, or must it be the one specified?

Thank you very much for this repo! It helped a great deal!

**Comment by koiker** [comment]
Hi jppdpf,

The prime is the 4096bit group in the RFC.
More info here: https://www.ietf.org/rfc/rfc5054.txt

**Comment by jppdpf** [comment]
Thank you for the quick reply! :)

**Comment by jppdpf** [comment]
I believe the prime is the 3096-bit in the RFC5054. And the RFC specifies 5 as the generator, but 2 is being used.

This 3072 prime and 2 generator combination I saw in the [RFC3526]( https://www.ietf.org/rfc/rfc3526.txt) on group assigned id 15.

I'm a noob in this SRP mechanism just wanted to point out my findings.

**Comment by koiker** [comment]
Hey, you are correct. The prime is 3096-bit. But I can't answer the reason for the generator 2 instead of 5.
The algorithm used here I've read from the AWS SDK like here: https://github.com/aws/amazon-cognito-identity-js/blob/master/src/AuthenticationHelper.js#L49
As all code examples use generator 2, I used the same here.
